base:
  config:
    nacos:
      hostname: localhost
      port: 8848

spring:
  application:
    # 应用名称
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    # 使用 Nacos 作为服务注册发现
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        - id: SERVER-OAUTH2
          uri: lb://server-oauth2
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: SERVER-PROFILE
          uri: lb://server-profile
          predicates:
            - Path=/api/profile/**, /api/users/**, /api/netmanager/**
          filters:
            - StripPrefix=1

server:
  port: 8888

# 配置日志级别
logging:
  level:
    org.springframework.cloud.gateway: debug
